layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 100
  exclude:
    archived: false
    forks: true
    projects:
      - newnishad
      - Goods-Distribution-System
      - SMS-Ticket-Booking-System
      - clipping

social_media:
  # behance: your_username
  # dribbble: your_username
  facebook: nisadrehman
  # hackerrank: your_username
  instagram: newnishad
  # keybase: your_username
  linkedin: nisadrahman
  # mastodon: your_username
  # medium: your_username
  # stackoverflow: your_user_id
  # telegram: your_username
  # twitter: your_username
  # unsplash: your_username
  # vk: your_username
  # website: http://your_website_url
  # youtube: your_username

topics:
  - name: Python
    web_url: https://www.python.org/
    image_url: https://camo.githubusercontent.com/888e388801f947dec7c3d843942c277af25fe2b1aed1821542c4e711f210312a/68747470733a2f2f75706c6f61642e77696b696d656469612e6f72672f77696b6970656469612f636f6d6d6f6e732f7468756d622f632f63332f507974686f6e2d6c6f676f2d6e6f746578742e7376672f37363870782d507974686f6e2d6c6f676f2d6e6f746578742e7376672e706e67

  - name: Javascript
    web_url: https://www.javascript.com/
    image_url: https://upload.wikimedia.org/wikipedia/commons/thumb/6/6a/JavaScript-logo.png/480px-JavaScript-logo.png

  - name: Flutter
    web_url: https://flutter.dev/
    image_url: https://www.gstatic.com/images/branding/product/2x/flutter_96dp.png
    
  - name: Node.js
    web_url: https://nodejs.org
    image_url: https://upload.wikimedia.org/wikipedia/commons/thumb/d/d9/Node.js_logo.svg/1200px-Node.js_logo.svg.png
    
  - name: Django
    web_url: https://www.djangoproject.com
    image_url: https://www.fullstackpython.com/img/logos/django.png
